### ISSUE TITLE
gradio app: No such file or directory: 'campplus_cn_common.bin'

### ISSUE THREAD

**Issue by O-O1024** [Plachtaa/seed-vc#10]
运行出错了：
```
Traceback (most recent call last):
  File "/root/seed-vc/app.py", line 34, in <module>
    campplus_model.load_state_dict(torch.load(config['model_params']['style_encoder']['campplus_path'], map_location='cpu'))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'campplus_cn_common.bin'
```

另外下载的模型使用符号链接看不出原文件名称，不好查找

**Comment by Plachtaa** [comment]
campplus_cn_common.bin已修
模型下载以后再优化

**Comment by O-O1024** [comment]
> campplus_cn_common.bin已修 模型下载以后再优化

app.py 已经提供模型下载，现在可以删除了
