### ISSUE TITLE
Error opening ... System error.

### ISSUE THREAD

**Issue by drgrib** [Plachtaa/seed-vc#28]
I'm getting there error every time I try to run the eval command:
```
PS C:\Users\MyUsername\Drive\Files\go\src\github.com\Plachtaa\seed-vc> python inference.py --source C:\Users\MyUsername\Drive\Files\transfer\source.wav --target C:\Users\MyUsername\Drive\Files\transfer\reference.wav --output C:\Users\MyUsername\Drive\Files\transfer --diffusion-steps 100 --length-adjust 1.0 --inference-cfg-rate 0.7 --f0-condition True --auto-f0-adjust False --semi-tone-shift 0
Warning: Skipped loading some keys due to shape mismatch: {'estimator.input_pos'}
cfm loaded
length_regulator loaded
Loading weights from nvidia/bigvgan_v2_22khz_80band_256x
Removing weight norm...
100%|████████████████████████████████████████████████████████████████████████████████████████| 100/100 [06:06<00:00,  3.67s/it]
RTF: 14.033603395255914
Traceback (most recent call last):
  File "C:\Users\MyUsername\Drive\Files\go\src\github.com\Plachtaa\seed-vc\inference.py", line 278, in <module>
    main(args)
  File "C:\Users\MyUsername\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\MyUsername\Drive\Files\go\src\github.com\Plachtaa\seed-vc\inference.py", line 263, in main
    torchaudio.save(os.path.join(args.output, f"vc_{source_name}_{target_name}_{length_adjust}_{diffusion_steps}_{inference_cfg_rate}.wav"), vc_wave.cpu(), sr)
  File "C:\Users\MyUsername\AppData\Local\Programs\Python\Python310\lib\site-packages\torchaudio\_backend\utils.py", line 313, in save
    return backend.save(
  File "C:\Users\MyUsername\AppData\Local\Programs\Python\Python310\lib\site-packages\torchaudio\_backend\soundfile.py", line 44, in save
    soundfile_backend.save(
  File "C:\Users\MyUsername\AppData\Local\Programs\Python\Python310\lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 457, in save
    soundfile.write(file=filepath, data=src, samplerate=sample_rate, subtype=subtype, format=format)
  File "C:\Users\MyUsername\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 343, in write
    with SoundFile(file, 'w', samplerate, channels,
  File "C:\Users\MyUsername\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\MyUsername\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\Users\\MyUsername\\Drive\\Files\\transfer\\vc_C:\\Users\\MyUsername\\Drive\\Files\\transfer\\source_C:\\Users\\MyUsername\\Drive\\Files\\transfer\\reference_1.0_100_0.7.wav': System error.
```

I notice that there are install instructions that are unclear to me:
> Before that, make sure you have openvoice and cosyvoice repo correctly installed on `../OpenVoice/` and `../CosyVoice/` if you would like to run baseline evaluation.

What does this mean? Do `OpenVoice` and `CosyVoice` literally have to be cloned to the directory we have `seed-vc` in? And what do you mean by "installed"? Just cloned? I looked at [OpenVoice](https://github.com/myshell-ai/OpenVoice) and it is using a completely different Python setup using Anaconda as far as I can tell so I don't see how it would even work with this repo's installation, which isn't using Anaconda.

**Comment by Plachtaa** [comment]
Please read the instructions clearly, `eval.py` is for objective evaluation but the script you run is `inference.py`, the reason for your error is the path you are trying to write does not exist. To fix, change all "\" to "/" in your audio path

**Comment by drgrib** [comment]
Thanks for the quick response. You are right that I mixed up the instructions for the `eval` command with the `inference` command.

Changing all `\` to `/` worked, thanks. I also just tried the Gradio interface using `python app.py` and that worked as well.
