### ISSUE TITLE
Gradio API For App.py Not Working.

### ISSUE THREAD

**Issue by ArianaStar** [Plachtaa/seed-vc#32]
**Running** `app.py` **is working correctly & the Gradio inference works well, however, when trying out the API example in my own Python script I get a weird error.** 

(seeder) H:\AI\seed-vc>python api.py
Loaded as API: http://127.0.0.1:7860/ ✔
Traceback (most recent call last):
  File "H:\AI\seed-vc\api.py", line 5, in <module>
    source=handle_file('H:\AI\seed-vc\examples\reference\s1p1.wav'),
  File "C:\Users\Ariana\miniconda3\envs\seeder\lib\site-packages\gradio_client\utils.py", line 1109, in handle_file
    raise ValueError(
eference\s1p1.wav does not exist on local filesystem and is not a valid URL. 

**I've tried many things but it won't accept files from my PC why?**

**Comment by ArianaStar** [comment]
dw I figured it out I'll close this now
