### ISSUE TITLE
real-time-gui报错，config.json中sg_input_device 和 sg_output_device怎么写？

### ISSUE THREAD

**Issue by yc930401** [Plachtaa/seed-vc#36]
Traceback (most recent call last):
  File "/data2/yangcheng/github_projects/seed-vc-main/real-time-gui.py", line 1016, in <module>
    gui = GUI()
  File "/data2/yangcheng/github_projects/seed-vc-main/real-time-gui.py", line 320, in __init__
    self.launcher()
  File "/data2/yangcheng/github_projects/seed-vc-main/real-time-gui.py", line 378, in launcher
    data = self.load()
  File "/data2/yangcheng/github_projects/seed-vc-main/real-time-gui.py", line 358, in load
    self.input_devices_indices.index(sd.default.device[0])
ValueError: -1 is not in list

**Comment by Plachtaa** [comment]
感谢反馈，这个确实是代码有问题，把configs/inuse/config.json删了就可以了

**Comment by xfguo-ucas** [comment]
> 感谢反馈，这个确实是代码有问题，把configs/inuse/config.json删了就可以了

删了的话，没有这个文件更跑不起来吧

**Comment by Plachtaa** [comment]
> > 感谢反馈，这个确实是代码有问题，把configs/inuse/config.json删了就可以了
> 
> 删了的话，没有这个文件更跑不起来吧

没有`configs/configs.json`是跑不起来的，但是`configs/inuse/config.json`会自动创建，这个不影响

**Comment by JingyangXu1991** [comment]
configs/inuse/config.json这个文件自动创建后仍会报这个问题
