### ISSUE TITLE
Start using tags while working on master

### ISSUE THREAD

**Issue by asusdisciple** [Plachtaa/seed-vc#61]
For me the current master is broken. When using app_svc.py i get:

```
Traceback (most recent call last):
  File "/home/.../PycharmProjects/seed-vc/app_svc.py", line 443, in <module>
    main(args)
  File "/home/.../PycharmProjects/seed-vc/app_svc.py", line 427, in main
    gr.Interface(fn=voice_conversion,
  File "/home/.../PycharmProjects/seed-vc/.venv/lib/python3.10/site-packages/gradio/interface.py", line 190, in __init__
    super().__init__(
  File "/home/.../PycharmProjects/seed-vc/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1074, in __init__
    super().__init__(render=False, **kwargs)
TypeError: BlockContext.__init__() got an unexpected keyword argument 'share'
```

When using real_time_gui.py I get:

```
Traceback (most recent call last):
  File "/home/nils/PycharmProjects/seed-vc/real-time-gui.py", line 1117, in <module>
    gui = GUI(args)
  File "/home/.../PycharmProjects/seed-vc/real-time-gui.py", line 382, in __init__
    self.model_set = load_models(args)
  File "/home/..../PycharmProjects/seed-vc/real-time-gui.py", line 188, in load_models
    hift_gen.load_state_dict(torch.load(hift_config['pretrained_model_path'], map_location='cpu'))
  File "/home/.../PycharmProjects/seed-vc/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/.../PycharmProjects/seed-vc/.venv/lib/python3.10/site-packages/torch/serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/.../PycharmProjects/seed-vc/.venv/lib/python3.10/site-packages/torch/serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/hift.pt'
```

App_vc.py works fine. I would really advertise to use tags until you are sure the master is working properly to have some versioning.

**Comment by Plachtaa** [comment]
fixed both just now, thanks for your kind feedback. 
there are quite a lot scripts so I may not be able to check all of them, apologies🙏

**Comment by asusdisciple** [comment]
No worries, thanks for the awesome work! No reason to apologize for anything.
