### ISSUE TITLE
'cp' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by 120805481** [Plachtaa/seed-vc#89]
我在window训练的之后，执行训练命令报错
D:\ProgramData\anaconda3\envs\seed-vc\python.exe D:\BaiduNetdiskDownload\seed-vc\训练.py 
'cp' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\seed-vc\train.py", line 402, in <module>
    main(args)
  File "D:\BaiduNetdiskDownload\seed-vc\train.py", line 377, in main
    trainer = Trainer(
  File "D:\BaiduNetdiskDownload\seed-vc\train.py", line 53, in __init__
    self.train_dataloader = build_ft_dataloader(
  File "D:\BaiduNetdiskDownload\seed-vc\data\ft_dataset.py", line 80, in build_ft_dataloader
    dataset = FT_Dataset(data_path, spect_params, sr, batch_size)
  File "D:\BaiduNetdiskDownload\seed-vc\data\ft_dataset.py", line 48, in __init__
    assert len(self.data) != 0
AssertionError

Process finished with exit code 0

**Comment by Plachtaa** [comment]
changed `cp` command to shutil instead
